export const CARDS = [
  {id: 1, sort: 1, alt: 'mini1', src: 'src/assets/mini1.png'},
  {id: 2, sort: 1, alt: 'mini1-2', src: 'src/assets/mini1.png'},
  {id: 3, sort: 2, alt: 'mini2', src: 'src/assets/mini2.png'},
  {id: 4, sort: 2, alt: 'mini2-2', src: 'src/assets/mini2.png'},
  {id: 5, sort: 3, alt: 'mini3', src: 'src/assets/mini3.png'},
  {id: 6, sort: 3, alt: 'mini3-2', src: 'src/assets/mini3.png'},
  {id: 7, sort: 4, alt: 'mini4', src: 'src/assets/mini4.png'},
  {id: 8, sort: 4, alt: 'mini4-2', src: 'src/assets/mini4.png'},
  {id: 9, sort: 5, alt: 'mini5', src: 'src/assets/mini5.png'},
  {id: 10, sort: 5, alt: 'mini5-2', src: 'src/assets/mini5.png'},
  {id: 11, sort: 6, alt: 'mini6', src: 'src/assets/mini6.png'},
  {id: 12, sort: 6, alt: 'mini6-2', src: 'src/assets/mini6.png'},
  {id: 13, sort: 7, alt: 'mini7', src: 'src/assets/mini7.png'},
  {id: 14, sort: 7, alt: 'mini7-2', src: 'src/assets/mini7.png'},
];
